import { Roboto } from 'next/font/google'
import './globals.css'
import Header from './../components/Layout/Header';
import Footer from './../components/Layout/Footer';
import { SessionProvider } from 'next-auth/react';


const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
        <SessionProvider>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
        </main>
      </body>
    </html>
  );
}
